version: "3.8"

services:
  mongo:
    image: mongo:6
    container_name: task-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./server
    container_name: task-backend
    restart: always
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    volumes:
      - ./server/uploads:/app/uploads
    depends_on:
      - mongo

  frontend:
    build: ./client
    container_name: task-frontend
    restart: always
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:5000/api
    depends_on:
      - backend

volumes:
  mongo_data:
